version: "2.2"
services:

  db:
    image: postgres:11-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: 1234
    volumes:
      - postgres:/var/lib/postgresql/data

  backup:
    image: 0xff/postgres-backup
    build: ./
    restart: always
    init: true
    environment:
      PGPASSWORD: 1234
      CRONSCHEDULE: "* * * * *"
    volumes:
      - ./pg-backups:/pg-backups

volumes:
  postgres:
