version: "2.2"
services:
  db:
    image: postgres:11-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: 1234
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - internal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  backup:
    image: 0xff/postgres-backup
    restart: always
    environment:
      PGPASSWORD: 1234
      CRONSCHEDULE: "21 22 * * *"
      PGDUMPOPTIONS: "-F c -f /pg-backups/backup-$$(date +%u).dump"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - internal
    volumes:
      - ./pg-backups:/pg-backups
volumes:
  postgres:
networks:
  internal:
